apiv1/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from apiv1.views import *


router = routers.DefaultRouter()

urlpatterns = [
    url('', include(router.urls)),
    url(r'items/list/$', ItemsListView.as_view(), name='item_list'),
    url(r'items/list/(?P<order>[-\w]+)/$', ItemsListView.as_view(), name='item_list'),

    url(r'member/create/$', SaveMember.as_view(), name='create_member'),
    url(r'member/list/$', MemberListView.as_view(), name='member_list'),
 ]

conf/urls.py
from django.conf.urls import url

from conf.views import *

urlpatterns = [
     url(r'sms/template/$', MessageTemplatesView.as_view(), name='sms_template'),
     url(r'district/list/$', DistrictListView.as_view(), name='district_list'),
     url(r'district/create/$', DistrictCreateView.as_view(), name='district_create'),
     url(r'district/(?P<pk>[\w]+)/$', DistrictUpdateView.as_view(), name='district_edit'),
     url(r'county/create/$', CountyCreateView.as_view(), name='county_create'),
     url(r'county/list/$', CountyListView.as_view(), name='county_list'),
     url(r'county/(?P<pk>[\w]+)/$', CountyUpdateView.as_view(), name='county_edit'),

     url(r'sc/create/$', SubCountyCreateView.as_view(), name='subcounty_create'),
     url(r'sc/list/$', SubCountyListView.as_view(), name='subcounty_list'),
     url(r'sc/(?P<pk>[\w]+)/$', SubCountyUpdateView.as_view(), name='subcounty_edit'),
     url(r'village/create/$', VillageCreateView.as_view(), name='village_create'),
     url(r'village/list/$', VillageListView.as_view(), name='village_list'),
     url(r'village/(?P<pk>[\w]+)/$', VillageUpdateView.as_view(), name='village_edit'),
     url(r'payment/create/$', PaymentModeCreateView.as_view(), name='payment_create'),
     url(r'payment/list/$', PaymentModeListView.as_view(), name='payment_list'),
     url(r'payment/(?P<pk>[\w]+)/$', PaymentModeUpdateView.as_view(), name='payment_edit'),
     
     url(r'upload/location/$', LocationUploadView.as_view(), name='location_upload'),
    ]

supplier/urls.py
from django.conf.urls import url

from supplier.views.items import *
from supplier.views.supplier import SupplierListView, SupplierCreateView, SupplierUpdateView, SupplierUserListView, SupplierUserCreate

urlpatterns = [
    url(r'item/price/(?P<pk>[\w]+)/$', get_item_price, name='item_price'),
    url(r'item/edit/(?P<pk>[\w]+)/$', ItemUpdateView.as_view(), name='item_update'),
    url(r'item/list/$', ItemListView.as_view(), name='item_list'),
    url(r'item/create/$', ItemCreateView.as_view(), name='item_create'),
    url(r'(?P<supplier>[\w]+)/users/$', SupplierUserListView.as_view(), name='supplier_user'),
    url(r'(?P<supplier>[\w]+)/users/add/$', SupplierUserCreate.as_view(), name='supplier_user_add'),
    url(r'list/$', SupplierListView.as_view(), name='supplier_list'),
    url(r'add/$', SupplierCreateView.as_view(), name='supplier_create'),
    url(r'edit/(?P<pk>[\w]+)/$', SupplierUpdateView.as_view(), name='supplier_edit'),



]

umis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from conf import urls as conf_urls
from supplier import urls as supplier_url
from userprofile import urls as profile_urls
from apiv1 import urls as api_urls
from system.views import CooperativesListView, UnionListView, UnionCreateView, UnionUpdateView, MembersListView, AgentListView, MembersOrderListView, UnionDeleteView


from dashboard.views import DashboardView
from userprofile.views.authentication import LoginView, LogoutView
from conf.views import Handle404, Handle403

handler404 = Handle404.as_view()
handler403 = Handle403.as_view()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^conf/', include(conf_urls, namespace='conf')),
    url(r'^supplier/', include(supplier_url, namespace='supplier')),
    url(r'^profile/', include(profile_urls, namespace='profile')),
    url(r'^apiv1/', include(api_urls, namespace='api')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^union/$', UnionListView.as_view(), name='union_list'),
    url(r'^union/create/$', UnionCreateView.as_view(), name='union_create'),
    url(r'^union/create/(?P<pk>[\w]+)/$', UnionUpdateView.as_view(), name='union_update'),
    url(r'^union/delete/(?P<pk>[\w]+)/$', UnionDeleteView.as_view(), name='union_delete'),
    url(r'^cooperative/$', CooperativesListView.as_view(), name='cooperative_list'),
    url(r'^member/$', MembersListView.as_view(), name='member_list'),
    url(r'^agent/$', AgentListView.as_view(), name='agent_list'),
    url(r'^orders/$', MembersOrderListView.as_view(), name='order_list'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.conf.urls import url

from userprofile.views.authentication import *
from userprofile.views.user_managment import *

urlpatterns = [
    url(r'access/group/list/$', AccessLevelGroupListView.as_view(), name='ag_list'),
     url(r'access/group/create/$', AccessLevelGroupCreateView.as_view(), name='ag_create'),
     url(r'access/group/(?P<pk>[\w]+)/$', AccessLevelGroupUpdateView.as_view(), name='ag_edit'),
     url(r'access/list/$', AccessLevelListView.as_view(), name='access_list'),
     url(r'access/create/$', AccessLevelCreateView.as_view(), name='access_create'),
     url(r'access/(?P<pk>[\w]+)/$', AccessLevelUpdateView.as_view(), name='access_edit'),
     url(r'group/list/$', GroupListView.as_view(), name='group_list'),
     url(r'group/create/$', GroupCreateView.as_view(), name='group_create'),
     url(r'group/(?P<pk>[\w]+)/$', GroupUpdateView.as_view(), name='group_edit'),
     url(r'password/change/$', ChangePasswordView.as_view(), name='password_edit'),
     url(r'password/change/(?P<pk>[\w]+)/$', AdminChangePasswordView.as_view(), name='admin_password_edit'),
     url(r'create/$', UserProfileCreateView.as_view(), name='user_create'),
     url(r'list/$', UserProfileListView.as_view(), name='user_list'),
     url(r'(?P<pk>[\w]+)/$', UserProfileCreateView.as_view(), name='user_edit'),
    ]

templates/base.html
<!doctype html>
{% load i18n %}
{% load static %}
<!--[if lte IE 9]> <html class="lte-ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html lang="en"> <!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Remove Tap Highlight on Windows Phone IE -->
    <meta name="msapplication-tap-highlight" content="no"/>

    
    <link rel="icon" type="image/png" href="{% static 'assets/img/fvicon_16.png' %}" sizes="16x16">
    <link rel="icon" type="image/png" href="{% static 'assets/img/fvicon_32.png' %}" sizes="32x32">


    <title>MY-KOOP</title>

    <!-- additional styles for plugins -->
        <!-- weather icons -->
        <link rel="stylesheet" href="{% static 'bower_components/weather-icons/css/weather-icons.min.css' %}" media="all">
        <!-- metrics graphics (charts) -->
        <link rel="stylesheet" href="{% static 'bower_components/metrics-graphics/dist/metricsgraphics.css' %}">
        <!-- chartist -->
        <link rel="stylesheet" href="{% static 'bower_components/chartist/dist/chartist.min.css' %}">
    
    <!-- uikit -->
    <link rel="stylesheet" href="{% static 'bower_components/uikit/css/uikit.almost-flat.min.css' %}" media="all">

    <!-- flag icons -->
    <link rel="stylesheet" href="{% static 'assets/icons/flags/flags.min.css' %}" media="all">

    <!-- altair admin -->
    <link rel="stylesheet" href="{% static 'assets/css/main.min.css' %}" media="all">

    <!-- matchMedia polyfill for testing media queries in JS -->
    <!--[if lte IE 9]>
        <script type="text/javascript" src="{% static 'bower_components/matchMedia/matchMedia.js' %}"></script>
        <script type="text/javascript" src="{% static 'bower_components/matchMedia/matchMedia.addListener.js' %}"></script>
    <![endif]-->
    <style>
        hr {
            margin: 0; !important
       }
       .uk-text-right{ text-align: right}
    </style>
    {% block style %}{% endblock %}

</head>
<body class=" sidebar_main_open sidebar_main_swipe header_full  {% block app_theme %} app_theme_f {% endblock %}">
    <!-- main header -->
    <header id="header_main">
        <div class="header_main_content">
            <nav class="uk-navbar">
                  <div class="main_logo_top">
                        <h2><a href="." style="color:#fff !important;"><img src="{% static 'assets/img/logo_menu.png' %}" alt="" width="50"/>MY-KOOP</a></h2>
                   </div>
                <!-- main sidebar switch -->
                <a href="#" id="sidebar_main_toggle" class="sSwitch sSwitch_left">
                    <span class="sSwitchIcon"></span>
                </a>
                
                <!-- secondary sidebar switch -->
                <a href="#" id="sidebar_secondary_toggle" class="sSwitch sSwitch_right sidebar_secondary_check">
                    <span class="sSwitchIcon"></span>
                </a>
                
                    <div class="uk-navbar-flip">
                    <ul class="uk-navbar-nav user_actions">
                        <li><a href="#" id="full_screen_toggle" class="user_action_icon uk-visible-large"><i class="material-icons md-24 md-light">&#xE5D0;</i></a></li>
                        <li><a href="#" id="main_search_btn" class="user_action_icon"><i class="material-icons md-24 md-light">&#xE8B6;</i></a></li>
                        <li data-uk-dropdown="{mode:'click',pos:'bottom-right'}">
                            <a href="#" class="user_action_image">
                                <img class="md-user-image" src="{% static 'assets/img/avatars/user.png' %}" alt=""/>
                                <span class="uk-text-bold">{{ request.user.username }}</span>
                            </a>
                            <div class="uk-dropdown uk-dropdown-small">
                                <ul class="uk-nav js-uk-prevent">
                                    <li><a href="{% url 'profile:password_edit' %} ">Change Password</a></li>
                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <div class="header_main_search_form">
            <i class="md-icon header_main_search_close material-icons">&#xE5CD;</i>
            <form class="uk-form">
                <input type="text" class="header_main_search_input" />
                <button class="header_main_search_btn uk-button-link"><i class="md-icon material-icons">&#xE8B6;</i></button>
            </form>
        </div>
    </header><!-- main header end -->
    <!-- main sidebar -->
    <aside id="sidebar_main">
        
        <div class="sidebar_main_header" style="height:auto !important; padding-top: 5px;">
            <!--<div class="sidebar_logo">
                <a href="index.html" class="sSidebar_hide"><img src="assets/img/logo_main.png" alt="" height="15" width="71"/>sas</a>
                <a href="index.html" class="sSidebar_show"><img src="assets/img/logo_main_small.png" alt="" height="32" width="32"/>asas</a>
            </div>-->
            <div class="sidebar_actions uk-text-center" >
                <h4 style="color: #000 !important;"><span class="uk-text-bold">{% if request.user.is_superuser %}SUPERUSER {% else %}{{ request.user.profile.access_level }}{% endif %}</span>
                <small></small></h4>
                
            </div>
        </div>
        
        <div class="menu_section">
            <ul>
                <li {% if '_dashboard' in active %}class="current_section"{% endif %} title="Dashboard">
                    <a href="{% url 'dashboard' %}">
                        <span class="menu_icon"><i class="material-icons">&#xE871;</i></span>
                        <span class="menu_title">Dashboard</span>
                    </a>
                </li>
                <hr>
                <li {% if '_union' in active %}class="current_section"{% endif %} title="Union">
                    <a href="{% url 'union_list' %}">
                        <span class="menu_icon"><i class="material-icons">&#xE871;</i></span>
                        <span class="menu_title">Union</span>
                    </a>
                </li>
                <li {% if '_cooperative' in active %}class="current_section"{% endif %} title="Cooperative">
                    <a href="{% url 'cooperative_list' %}">
                        <span class="menu_icon"><i class="material-icons">&#xE871;</i></span>
                        <span class="menu_title">Cooperative</span>
                    </a>
                </li>
                <li {% if '_member' in active %}class="current_section"{% endif %} title="Member">
                    <a href="{% url 'member_list' %}">
                        <span class="menu_icon"><i class="material-icons">&#xE871;</i></span>
                        <span class="menu_title">Members</span>
                    </a>
                </li>
                <li {% if '_agent' in active %}class="current_section"{% endif %} title="Agent">
                    <a href="{% url 'agent_list' %}">
                        <span class="menu_icon"><i class="material-icons">&#xE871;</i></span>
                        <span class="menu_title">Agents</span>
                    </a>
                </li>
                <li {% if '_order' in active %}class="current_section"{% endif %} title="Agent">
                    <a href="{% url 'order_list' %}">
                        <span class="menu_icon"><i class="material-icons">&#xE871;</i></span>
                        <span class="menu_title">Orders</span>
                    </a>
                </li>
                <li {% if '_supplier' in active %}class="current_section"{% endif %} title="Supplier">
                    <a href="{% url 'supplier:supplier_list' %}">
                        <span class="menu_icon"><i class="material-icons">&#xE871;</i></span>
                        <span class="menu_title">Supplier</span>
                    </a>
                </li>
                <li {% if '_supplier' in active %}class="current_section"{% endif %} title="Supplier">
                    <a href="{% url 'supplier:item_list' %}">
                        <span class="menu_icon"><i class="material-icons">&#xE871;</i></span>
                        <span class="menu_title">Items</span>
                    </a>
                </li>
                {% if request.user.is_superuser %}
                 <li>
                    <a href="#">
                        <span class="menu_icon"><i class="material-icons">account_circle</i></span>
                        <span class="menu_title">System Users</span>
                    </a>
                    <ul>
                        <li {% if '__user' in active %}class="act_item"{% endif %}><a href="{% url 'profile:user_list' %}">User</a></li>
                        <li {% if '__acess_level' in active %}class="act_item"{% endif %}><a href="{% url 'profile:access_list' %}">Access Level</a></li>
                        <li {% if '__group' in active %}class="act_item"{% endif %}><a href="{% url 'profile:group_list' %}">Group Permission</a></li>
                        <li {% if '__access_group' in active %}class="act_item"{% endif %}><a href="{% url 'profile:ag_list' %}">Access Group</a></li>
                    </ul>
                </li>
                {% endif %}

            </ul>
            
        </div>
        <div class="menu_bottom" style="padding: 8px 20px; height: auto; margin-top: 20px">
            <img src="{% static 'assets/img/logo.png' %}" width="100" style="bottom: 0px;">
        </div>
    </aside><!-- main sidebar end -->

    <div id="page_content">
        <div id="page_content_inner">
            {% include 'message.html' %}
            {% block page_content %}{% endblock %}

        </div>
    </div>

    <!-- common functions -->
    <script src="{% static 'assets/js/common.min.js' %}"></script>
    <!-- uikit functions -->
    <script src="{% static 'assets/js/uikit_custom.min.js' %}"></script>
    <!-- altair common functions/helpers -->
    <script src="{% static 'assets/js/altair_admin_common.min.js' %}"></script>
    {% block page_specific_scripts %}{% endblock %}
    
</body>
</html>

templates/confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% load my_custom_tags %} 

{% block style %}
    <!-- additional styles for plugins -->
    <!-- dropify -->
    <link rel="stylesheet" href="{% static 'assets/skins/dropify/css/dropify.css' %}">
    
{% endblock %}
{% block page_content %}
<h3 class="heading_b uk-margin-bottom">Delete Form</h3>
   <div class="md-card">
        <div class="md-card-content">
            <form method="post" class="new-event-form" role="role">
                {% csrf_token %}
                <div class="uk-grid">
                    <div class="uk-width-1-1">
                        <h2>Are you sure you want to delete "{{ object }}"?</h2>
                        <p class="uk-text-danger uk-margin-remove">Please note that delete this item may affect other items created elsewhere</p>
                        {% for model_name, object_count in model_count %}
                            <b>{{ model_name|capfirst }}</b> {{ object_count }} <br>
                        {% endfor %}
                        {{ deletable_objects|unordered_list }}
                    </div>
                </div>
                <div class="uk-grid">
                    <div class="uk-width-1-1">
                        <input type="submit" value="Confirm" class="md-btn md-btn-danger">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/message.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="uk-alert uk-alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/status_text.html
{% if field == 'ACCEPTED' or field == 'SUCCESSFUL' %}
<span class="uk-text-success uk-margin-remove">{{ field }}</span>
{% endif %}
{% if field == 'REJECTED' or field == 'FAILED' %}
<span class="uk-text-danger uk-margin-remove">{{ field }}</span>
{% endif %}
{% if field == 'PENDING' %}
<span class="uk-text-warning uk-margin-remove">{{ field }}</span>
{% endif %}
  