conf/urls.py
from django.conf.urls import url

from conf.views import *

urlpatterns = [
     url(r'sms/template/$', MessageTemplatesView.as_view(), name='sms_template'),
     url(r'district/list/$', DistrictListView.as_view(), name='district_list'),
     url(r'district/create/$', DistrictCreateView.as_view(), name='district_create'),
     url(r'district/(?P<pk>[\w]+)/$', DistrictUpdateView.as_view(), name='district_edit'),
     url(r'county/create/$', CountyCreateView.as_view(), name='county_create'),
     url(r'county/list/$', CountyListView.as_view(), name='county_list'),
     url(r'county/(?P<pk>[\w]+)/$', CountyUpdateView.as_view(), name='county_edit'),

     url(r'sc/create/$', SubCountyCreateView.as_view(), name='subcounty_create'),
     url(r'sc/list/$', SubCountyListView.as_view(), name='subcounty_list'),
     url(r'sc/(?P<pk>[\w]+)/$', SubCountyUpdateView.as_view(), name='subcounty_edit'),
     url(r'village/create/$', VillageCreateView.as_view(), name='village_create'),
     url(r'village/list/$', VillageListView.as_view(), name='village_list'),
     url(r'village/(?P<pk>[\w]+)/$', VillageUpdateView.as_view(), name='village_edit'),
     url(r'payment/create/$', PaymentModeCreateView.as_view(), name='payment_create'),
     url(r'payment/list/$', PaymentModeListView.as_view(), name='payment_list'),
     url(r'payment/(?P<pk>[\w]+)/$', PaymentModeUpdateView.as_view(), name='payment_edit'),
     
     url(r'upload/location/$', LocationUploadView.as_view(), name='location_upload'),
    ]

umis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from conf import urls as conf_urls
from supplier import urls as supplier_url
from userprofile import urls as profile_urls
from apiv1 import urls as api_urls
from system.views import CooperativesListView, UnionListView, UnionCreateView, UnionUpdateView, MembersListView, AgentListView, MembersOrderListView, UnionDeleteView


from dashboard.views import DashboardView
from userprofile.views.authentication import LoginView, LogoutView
from conf.views import Handle404, Handle403

handler404 = Handle404.as_view()
handler403 = Handle403.as_view()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^conf/', include(conf_urls, namespace='conf')),
    url(r'^supplier/', include(supplier_url, namespace='supplier')),
    url(r'^profile/', include(profile_urls, namespace='profile')),
    url(r'^apiv1/', include(api_urls, namespace='api')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^union/$', UnionListView.as_view(), name='union_list'),
    url(r'^union/create/$', UnionCreateView.as_view(), name='union_create'),
    url(r'^union/create/(?P<pk>[\w]+)/$', UnionUpdateView.as_view(), name='union_update'),
    url(r'^union/delete/(?P<pk>[\w]+)/$', UnionDeleteView.as_view(), name='union_delete'),
    url(r'^cooperative/$', CooperativesListView.as_view(), name='cooperative_list'),
    url(r'^member/$', MembersListView.as_view(), name='member_list'),
    url(r'^agent/$', AgentListView.as_view(), name='agent_list'),
    url(r'^orders/$', MembersOrderListView.as_view(), name='order_list'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

system/models.py
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import qrcode
import StringIO
from datetime import datetime, date
from django.db import models
from django.db.models import F, Sum
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.core.files.uploadedfile import InMemoryUploadedFile

from conf.models import District, County, SubCounty, Village, Parish, PaymentMethod
# from partner.models import PartnerTrainingModule


class Union(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)
    token = models.CharField(max_length=255)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'union'

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class Cooperative(models.Model):
    name = models.CharField(max_length=150, unique=True)
    logo = models.ImageField(upload_to='cooperatives/', null=True, blank=True)
    code = models.CharField(max_length=150, unique=True, null=True, blank=True)
    district = models.ForeignKey(District, null=True, blank=True, on_delete=models.CASCADE)
    sub_county = models.ForeignKey(SubCounty, null=True, blank=True, on_delete=models.CASCADE)
    address = models.TextField(null=True, blank=True)
    phone_number = models.CharField(max_length=12, null=True, blank=True)
    contact_person_name = models.CharField(max_length=150)
    contribution_total = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    shares = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    is_active = models.BooleanField(default=0)
    send_message = models.BooleanField(default=0,
                                       help_text='If not set, the cooperative member will not receive SMS\'s when sent.')
    date_joined = models.DateField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'cooperative'

    def __unicode__(self):
        return self.name


class NECPAManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).using('necpa')


class UOSPAManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).using('uospa')


class WACUManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).using('wacu')


class ODFAManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).using('odfa')


class CooperativeMember(models.Model):
    title = (
        ('Mr', 'Mr'),
        ('Miss', 'Miss'),
        ('Mrs', 'Mrs'),
        ('Dr', 'Dr'),
        ('Prof', 'Prof'),
        ('Hon', 'Hon'),
    )
    cooperative = models.ForeignKey(Cooperative, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='member/', null=True, blank=True)
    member_id = models.CharField(max_length=150, unique=True, null=True, blank=True)
    title = models.CharField(max_length=25, choices=title, null=True, blank=True)
    surname = models.CharField(max_length=150)
    first_name = models.CharField(max_length=150, null=True, blank=True)
    other_name = models.CharField(max_length=150, null=True, blank=True)
    is_refugee = models.BooleanField(default=False)
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=(('Male', 'Male'), ('Female', 'Female')), null=True,
                              blank=True)
    maritual_status = models.CharField(max_length=10, null=True, blank=True,
                                       choices=(('Single', 'Single'), ('Married', 'Married'),
                                                ('Widowed', 'Widow'), ('Divorced', 'Divorced')))
    id_number = models.CharField(max_length=150, null=True, blank=True)
    id_type = models.CharField(max_length=150, null=True, blank=True,
                               choices=(('nin', 'National ID'), ('dl', 'Drivers Lisence'),
                                        ('pp', 'PassPort'), ('o', 'Other')))
    phone_number = models.CharField(max_length=12, null=True, blank=True)
    other_phone_number = models.CharField(max_length=12, null=True, blank=True)
    email = models.EmailField(max_length=254, null=True, blank=True)
    district = models.ForeignKey(District, null=True, blank=True, on_delete=models.CASCADE)
    county = models.ForeignKey(County, null=True, blank=True, on_delete=models.CASCADE)
    sub_county = models.ForeignKey(SubCounty, null=True, blank=True, on_delete=models.CASCADE)
    parish = models.ForeignKey(Parish, null=True, blank=True, on_delete=models.CASCADE)
    village = models.CharField(max_length=150, null=True, blank=True)
    address = models.CharField(max_length=150, null=True, blank=True)
    gps_coodinates = models.CharField(max_length=150, null=True, blank=True)
    coop_role = models.CharField(max_length=150, choices=(
    ('Chairperson', 'Chairperson'), ('Vice', 'Vice'), ('Treasurer', 'Treasurer'),
    ('Secretary', 'Secretary'), ('Committee Member', 'Committee Member'), ('Member', 'Member')))
    # cotton_acreage = models.DecimalField(max_digits=10, decimal_places=2, default=0, null=True, blank=True)
    # soya_beans_acreage = models.DecimalField(max_digits=10, decimal_places=2, default=0, null=True, blank=True)
    # soghum_acreage = models.DecimalField(max_digits=10, decimal_places=2, default=0, null=True, blank=True)
    land_acreage = models.DecimalField(max_digits=10, decimal_places=2, default=0, null=True, blank=True)
    product = models.CharField(max_length=255, null=True, blank=True)
    shares = models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=True)
    share_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=True)
    collection_amount = models.DecimalField(max_digits=32, decimal_places=2, default=0, blank=True)
    collection_quantity = models.DecimalField(max_digits=32, decimal_places=2, default=0, blank=True)
    paid_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=True)
    is_active = models.BooleanField(default=1)
    qrcode = models.ImageField(upload_to='qrcode', blank=True, null=True)
    create_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'cooperative_member'

    def __unicode__(self):
        return "{} {}".format(self.surname, self.first_name)

    @property
    def get_name(self):
        return "%s %s" % (self.surname, self.first_name)

    def age(self):
        if self.date_of_birth:
            m = date.today() - self.date_of_birth
            return m.days / 365
        return 0


class Supplier(models.Model):
    name = models.CharField(max_length=255, unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'supplier'

    def __unicode__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=255, unique=True)
    supplier = models.ForeignKey(Supplier, null=True, blank=True, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'item'

    def __unicode__(self):
        return self.name


class MemberOrder(models.Model):
    cooperative = models.ForeignKey(Cooperative, on_delete=models.CASCADE)
    member = models.ForeignKey(CooperativeMember, on_delete=models.CASCADE)
    order_reference = models.CharField(max_length=255, blank=True)
    order_price = models.DecimalField(max_digits=20, decimal_places=2, default=0, blank=True)
    status = models.CharField(max_length=255, default='PENDING')
    order_date = models.DateTimeField()
    accept_date = models.DateTimeField(null=True, blank=True)
    reject_date = models.DateTimeField(null=True, blank=True)
    reject_reason = models.CharField(max_length=120, null=True, blank=True)
    ship_date = models.DateTimeField(null=True, blank=True)
    delivery_accept_date = models.DateTimeField(null=True, blank=True)
    delivery_reject_date = models.DateTimeField(null=True, blank=True)
    delivery_reject_reason = models.CharField(max_length=120, null=True, blank=True)
    collect_date = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(User, blank=True, on_delete=models.CASCADE, related_name='order_created_by')
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'member_order'

    def __unicode__(self):
        return "%s" % self.order_reference or u''

    def get_orders(self):
        return OrderItem.objects.filter(order=self)


class OrderItem(models.Model):
    order = models.ForeignKey(MemberOrder, blank=True, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.DecimalField(max_digits=20, decimal_places=2)
    unit_price = models.DecimalField(max_digits=20, decimal_places=2, blank=True)
    price = models.DecimalField(max_digits=20, decimal_places=2, blank=True)
    created_by = models.ForeignKey(User, blank=True, on_delete=models.CASCADE, related_name='created_by')
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

payment/templates/payment/memberpayment_form.html
{% extends 'base.html' %}
{% load static %}
{% load my_custom_tags %}

{% block style %}
    <!-- additional styles for plugins -->
     <!-- kendo UI -->
    <link rel="stylesheet" href="{% static 'bower_components/kendo-ui/styles/kendo.common-material.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'bower_components/kendo-ui/styles/kendo.material.min.css' %}"/>
    <style>
        .k-combobox{
            width: 100% !important;
        }
    </style>
    
{% endblock %}
{% block page_content %}
    <h3 class="heading_b uk-margin-bottom">Payment Form</h3>
    <div class="md-card">
        <div class="md-card-content">
    
            <form method="POST" class="new-event-form" role="role">
               {% csrf_token %}
               
                   <div class="uk-grid" data-uk-grid-margin="">
                       
                       <div class="uk-width-medium-1-2">
                           <div class="md-input-wrapper">
                               {% include "form/field.html" with field=form.cooperative input_group_add_on='<i class="uk-input-group-icon uk-icon-building "></i>' %}
                           </div>
                       </div>
                       
                       <div class="uk-width-medium-1-2">
                           <div class="md-input-wrapper">
                               {% include "form/field.html" with field=form.member input_group_add_on='<i class="uk-input-group-icon uk-icon-user "></i>' %}
                           </div>
                       </div>
                   </div>
                   <div class="uk-grid" data-uk-grid-margin="">
                     <div class="uk-width-medium-1-2">
                           <div class="md-input-wrapper">
                               {% include "form/field.html" with field=form.payment_method  input_group_add_on='<i class="uk-input-group-icon uk-icon-calendar"></i>' %}
                           </div>
                       </div>
                   </div>
                   <div class="uk-grid" data-uk-grid-margin="">
                       <div class="uk-width-medium-1-2">
                           <div class="md-input-wrapper">
                               {% include "form/field.html" with field=form.payment_date|htmlattributes:"data-uk-datepicker={format:'YYYY-MM-DD'}, class=md-input"  input_group_add_on='<i class="uk-input-group-icon uk-icon-calendar"></i>' %}
                           </div>
                       </div>
                        <div class="uk-width-medium-1-2">
                           <div class="md-input-wrapper">
                               {% include "form/field.html" with field=form.amount input_group_add_on='<i class="uk-input-group-icon uk-icon-money "></i>' %}
                           </div>
                       </div>
                   </div>
               
                   
                
                       <div class="uk-grid uk-text-right" data-uk-grid-margin="">
                           
                           <div class="uk-width-medium-1-1 uk-text-right">
                               <button href="#" id="id_submit" class="md-btn md-btn-primary uk-margin-small-top">SUBMIT</button>
                           </div>
                       </div>
                   
           </form>
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- page specific plugins -->
    <!-- ionrangeslider -->
    <script src="{% static 'bower_components/ion.rangeslider/js/ion.rangeSlider.min.js' %}"></script>

  <!-- inputmask-->
    <script src="{% static 'bower_components/jquery.inputmask/dist/jquery.inputmask.bundle.js' %}"></script>
    <!--  forms advanced functions -->
    <script src="{% static 'assets/js/pages/forms_advanced.min.js' %}"></script>
    
    <!--  dropify -->
    <script src="{% static 'assets/js/custom/dropify/dist/js/dropify.min.js' %}"></script>

    <!--  form file input functions -->
    <script src="{% static 'assets/js/pages/forms_file_input.min.js' %}"></script>
    
    <!-- kendo UI -->
    <script src="{% static 'assets/js/kendoui_custom.min.js' %}"></script>

    <!--  kendoui functions -->
    <script src="{% static 'assets/js/pages/kendoui.min.js' %}"></script>
     <script src="{% static 'bower_components/jquery.formset.js' %}"></script>
    <script>
        var share_value = 0;
         $("#id_order-0-price").addClass( " label-fixed " );
        $('.id_item').kendoComboBox({
            filter: "contains",
            suggest: true
        });
        
        $('#id_item').kendoComboBox({
            filter: "contains",
            suggest: true
        });
        
        $("#id_item").on('change', function() {
            $("#id_price").val('');
            $("#id_quantity").val('');
        });
        
        $("#id_quantity").on('input', function() {
            var product = $("#id_item").val();
            var quantity = $("#id_quantity").val();
            var url = "http://"+window.location.host +"/product/item/price/"+product
            $.get(url, function(data, status){
                var total = quantity * data.price
                $('#id_price').val(total)
            });
        });
        
        $('.link-formset').formset({
            addText: 'add + ',
            deleteText: 'remove -',
            prefix : 'order'
        });
    
        $('.link-formset-2').formset({
            addText: 'add + ',
            deleteText: 'remove -',
            prefix: 'patterns'
        });
        
        function refreshInput (args) {
            var id = $(args).attr('id');
            var price = id.replace("item", "price");
            var quantity = id.replace("item", "quantity");
            $("#"+quantity).val('')
            $("#"+price).val('')
        }
        
        function calculatePrice(args) {
            var quantity = $(args).attr('id');
            var price = quantity.replace("quantity", "price");
            var item = quantity.replace("quantity", "item");
            
            var it = $("#"+item).val()
            
            var url = "http://"+window.location.host +"/product/item/price/"+it
            $.get(url, function(data, status){
                var total = $("#"+quantity).val() * data.price
                $("#"+price).val(total)
            });
        }
        
        
        //$("#id_village").empty();
        $("#id_cooperative").change(function () {
            var url = "{% url 'coop:ajax_load_members' %}"  // get the url of the `load_cities` view
            var cooperative = $(this).val();  // get the selected country ID from the HTML input
      
            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                data: {
                    'cooperative': cooperative       // add the country id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_cities` view function
                    $("#id_member").html(data);  // replace the contents of the city input with the data that came from the server
                }
            });
      
        });
            
    </script>
    
{% endblock %}
    

payment/templates/payment/memberpayment_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Payments</h4>
        </div>
        <div class="uk-width-medium-1-2 uk-text-right">
            <a href="{% url 'payment:download' %}" class="md-btn md-btn-success ">Download Excel</a>
            {% if request.user.profile.is_union %}
                 <a href="{% url 'payment:create' %}" class="md-btn md-btn-success ">Add Payment</a>
            {% endif %}
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table id="dt_tableTools" class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Payment Date</th>
                        <th>Coop</th>
                        <th>Member</th>
                        <th>Amount</th>
                        <th>Reference</th>
                        <th>Status</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.payment_date| date:"d, M Y" }}</td>
                               <td>{{ item.cooperative }}</td>
                                <td>{{ item.member }}</td>
                                <td>{{ item.amount }}</td>
                                <td>{{ item.transaction_id }}</td>
                                <td>{{ item.status }}</td>
                                <td>{{ item.update_date }}</td>
                                <td><a href="" class="uk-float-right"><i class="md-icon material-icons">&#xE254;</i></a></td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
           
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- datatables -->
    <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <!-- datatables colVis-->
    <script src="{% static 'bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
<!-- datatables tableTools-->
    <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>
    <!-- datatables custom integration -->
    <script src="{% static 'assets/js/custom/datatables_uikit.min.js' %}"></script>

    <!--  datatables functions -->
    <script src="{% static 'assets/js/pages/plugins_datatables.min.js' %}"></script>
{% endblock %}